### PR TITLE
better code block formatting

### PR DESCRIPTION
**Pull request by dstokes**

### CODE REVIEW

**Comment by dstokes** [comment]
screen shot 2015-03-07 at 4 27 06 pm

**Comment by 8bitDesigner** [comment]
Looks good, but your  `background: rgba(0,0,0,0.05);` line adds a background on top of the one that's applied to some tables:

screen shot 2015-03-07 at 16 43 40

**Comment by dstokes** [comment]
my css foo is weak. can't remember how to select parent elements relatively

**Comment by dstokes** [comment]
tables are using the bgcolor attr, added `!important`, not sure if there's a better way to handle it

**Comment by 8bitDesigner** [comment]
:+1:

**Pull request merged**
